### PR TITLE
fixed message to provide device IP

### PR DESCRIPTION
**Pull request by levackt**
A lil nitpick

### CODE REVIEW

**Comment by andytudhope** [comment]
I'll consider merging here if you figure out a way to get the `scan` script to exit gracefully once it has provided the IPs it finds - currently you have to `ctrl+c` to get out of it.
More than grammar fixes for contributor badges here I'm afraid 😉

**Comment by levackt** [comment]
No prob, pushed a stab but I still want to make sure it still handles multiple devices as expected.

**Comment by levackt** [comment]
Added a 10 second delay, the branch is a bit dirty so please let me know if I should redo the branch and resubmit PR before you reconsider merging.

**Comment by andytudhope** [comment]
Hey @levackt - please just squash the commits down to 1 here and then I will test and, if all is well, merge.

**Comment by levackt** [comment]
Closing to recreate with squashed commit from local master

**Pull request closed without merging**
